title: getting-started-with-translation
hero_image: images/banner.png
description: getting-started-with-translation description
version: 4
listed: false
copyedit: false
last_tested: "2019-01-23"
steps:
  - title: Introduction
  - title: What we translate
  - title: Our translation process
  - title: The tools you'll use
  - title: What's next?
